.dashDeckgl_js_metadata <- function() {
deps_metadata <- list(`dash_deckgl` = structure(list(name = "dash_deckgl",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'DashDeckgl.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDeckgl",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_deckgl` = structure(list(name = "dash_deckgl",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'deckgl.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDeckgl",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_deckgl` = structure(list(name = "dash_deckgl",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'vendor.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDeckgl",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_deckgl` = structure(list(name = "dash_deckgl",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'DashDeckgl.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDeckgl",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_deckgl` = structure(list(name = "dash_deckgl",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'deckgl.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDeckgl",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_deckgl` = structure(list(name = "dash_deckgl",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'vendor.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDeckgl",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_deckgl` = structure(list(name = "dash_deckgl",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_deckgl.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDeckgl",
all_files = FALSE), class = "html_dependency"),
`dash_deckgl` = structure(list(name = "dash_deckgl",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_deckgl.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDeckgl",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
